### ISSUE TITLE
"Object Added" message is sent even in delete mode

### ISSUE THREAD

**Issue by zcmoore** [zcmoore/DecisionTheater#7]
It looks like this is still being implemented.
Posting this issue as a reminder. Marking as "enhancement" for now

If the user is in delete mode, it should only send a delete message. We'll check the validity of the request server side, so it is not necessary to check it client side (although it would be beneficial).

**Comment by Williamgood** [comment]
A push didn't get merged for some reason, but fixed now. Can only delete a selected object.
